### ISSUE TITLE
Salvando documentos "no banco de dados" vs "em disco"

### ISSUE THREAD

**Issue by edo9k** [LDI-Ufes/sgc#2]
Criando a issue aqui pra não esquecer de discutir sobre isso depois.

https://github.com/LDI-Ufes/sgc/blob/6e1b7297cc2e25b25b08e4cfd334b1323fe53ae0/database/seeders/BondDocumentSeeder.php#L22

Sempre ouvi que não era uma boa ideia guardar documentos (binários) dentro do banco de dados. Que é ineficiente, que o arquivo ocupa mais espaço no banco do que no disco, que "pesa o banco" e etc. 

Na escala que essa aplicação provavelmente vai ser usada, não creio que venha fazer diferença. Ainda assim não curto a ideia de salvar no DB. Tenho mais simpatia com o método de salvar no arquivo em disco e salvar o caminho no banco. 

Para evitar que alguém adultere o arquivo no disco, dá pra salvar junto um hash do arquivo. SHA1 ou MD5 (que é velhão mas também é uma opção).

**Comment by marcoaureliocardoso** [comment]
It's a feature
